apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-history-server-config
  namespace: spark
data:
  spark-defaults.conf: |
    spark.history.fs.logDirectory=s3a://mynewsourcecodebkt/spark-logs/
    spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.endpoint=s3.amazonaws.com
    spark.history.fs.cleaner.enabled=true
    spark.history.fs.cleaner.interval=1d
    spark.history.fs.cleaner.maxAge=5d
    spark.history.retainedApplications=5
    spark.history.kerberos.enabled=false
