apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: spark
spec:
  selector:
    app: spark-history-server
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
  type: ClusterIP
