apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: spark #this project is already defined during spark-hitory-server
  source:
    repoURL: https://github.com/vknst96/spark.git #As this is public repo, no need to use ssh path, instead using https.
    targetRevision: localDockerK8s
    path: localDockerK8s/elasticsearch-k8s-manifests/elasticsearch-manifests
  destination:
    namespace: elastic
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
