apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app-name: spark-on-eks-client-mode
  name: spark-on-eks-client-mode-executor-pod-template-cm
  namespace: spark
data:
  executorpodtemplate-configmap-key: |
    apiVersion: v1
    kind: Pod
    spec:
      tolerations:
      - key: spot
        operator: Equal
        value: true
        effect: NoSchedule
      nodeSelector:
        sparkrole: executor
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: spark/app
                operator: In
                values:
                - spark-eks
            topologyKey: topology.kubernetes.io/zone
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: spark/app
                operator: NotIn
                values:
                - spark-eks
              - key: spark/component
                operator: In
                values:
                - executor
            topologyKey: kubernetes.io/hostname
