apiVersion: v1
kind: Pod
metadata:
  labels:
    spark-app-name: spark-on-eks-client-mode-res1
    spark-app-selector: spark-app-spark-on-eks-client-mode-res1
    spark-role: driver
    spark-version: 3.3.1
    spark/app: spark-eks
    spark/component: driver
  name: spark-on-eks-client-mode-res1-driver
  namespace: spark
spec:
  containers:
  - name: driver
    image: vknstudy96/pyspark-app:v1
    args:
    - driver
    - --properties-file
    - /opt/spark/conf/spark.properties
    - --class
    - org.apache.spark.deploy.PythonRunner
    - local:///opt/spark/work-dir/main.py
    - s3a://mysourcecodebkt/sourcedata/Restaurants_in_Wake_County.csv
    - s3a://mysourcecodebkt/sourcedata/Restaurants_in_Durham_County_NC.json
    imagePullPolicy: Always
    ports:
    - containerPort: 7078
      name: driver-rpc-port
      protocol: TCP
    - containerPort: 7079
      name: blockmanager
      protocol: TCP
    - containerPort: 4040
      name: spark-ui
      protocol: TCP
    resources:
      limits:
        memory: 2867Mi
      requests:
        cpu: "1"
        memory: 2867Mi
    env:
      - name: SPARK_USER
        value: ubuntu
      - name: SPARK_DRIVER_BIND_ADDRESS
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      - name: PYSPARK_PYTHON
        value: /usr/bin/python3
      - name: PYSPARK_DRIVER_PYTHON
        value: /usr/bin/python3
      - name: SPARK_LOCAL_DIRS
        value: /var/data/spark-b7a21648-5315-45d1-82a2-0f9fb0b394af
      - name: SPARK_CONF_DIR
        value: /opt/spark/conf
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-east-1
      - name: AWS_REGION
        value: us-east-1
      - name: AWS_ROLE_ARN
        value: arn:aws:iam::925042885928:role/eksctl-myEksCluster-addon-iamserviceaccount-Role1-1KRD6WHJ3MZ3B
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    volumeMounts:
      - mountPath: /opt/spark/pod-template
        name: pod-template-volume
      - mountPath: /var/data/spark-b7a21648-5315-45d1-82a2-0f9fb0b394af
        name: spark-local-dir-1
      - mountPath: /opt/spark/conf
        name: spark-conf-volume-driver
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: executorpodtemplate-configmap-key
        path: executor-pod-spec-template.yml
      name: spark-on-eks-client-mode-executor-pod-template-cm
    name: pod-template-volume
  - emptyDir: {}
    name: spark-local-dir-1
  - configMap:
      defaultMode: 420
      items:
      - key: spark.properties
        mode: 420
        path: spark.properties
      name: spark-on-eks-client-mode-res1-cm
    name: spark-conf-volume-driver
  serviceAccount: spark
  serviceAccountName: spark
  nodeSelector:
    noderole: spark
    sparkrole: driver
    topology.kubernetes.io/zone: us-east-1a
  restartPolicy: Never
