apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-history-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: spark
  source:
    repoURL: https://github.com/vknst96/spark.git #As this is public repo, no need to use ssh path.
    # repoURL: git@github.com:vknst96/argocd.git
    targetRevision: localDockerK8s
    path: spark\localDockerK8s\spark-k8s-manifests\spark-history-server
  destination:
    namespace: spark
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
